tasks:
  - init: yarn install && gp sync-done install
    command: yarn watch

  - name: Docs
    init: gp sync-await install
    command: yarn docs
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-preview
